nodeLinker: pnp

packageExtensions:
  react-scripts@*:
    dependencies:
      eslint-config-react-app: '*'
      eslint-import-resolver-node: '*'
      eslint-plugin-flowtype: '*'
      eslint-plugin-import: '*'
      eslint-plugin-jest: '*'
      eslint-plugin-testing-library: '*'
  styled-components@*:
    dependencies:
      react-is: '*'
  '@pmmmwh/react-refresh-webpack-plugin@*':
    dependencies:
      webpack-hot-middleware: '*'
    peerDependencies:
      webpack-hot-middleware: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-exec.cjs
    spec: '@yarnpkg/plugin-exec'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: '@yarnpkg/plugin-stage'

preferInteractive: true

yarnPath: .yarn/releases/yarn-berry.cjs
